# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-17.0.10.7-hotspot

# mod version info
mod_version = 1.5.0
artifact_minecraft_version = 1.20.1
minecraft_version = 1.20.1
forge_version = 47.1.43

# build dependency versions
mixin_version = 0.8.5
parchment_version = 2023.07.23

# embedded dependency versions
mixin_extras_version = 0.2.0

# mandatory dependency versions
create_minecraft_version = 1.20.1
create_version = 6.0.8
create_version_number = 291
flywheel_minecraft_version = 1.20.1
flywheel_version = 1.0.6-beta-266
registrate_version = MC1.20-1.3.3
jei_minecraft_version = 1.20.1
jei_version = 15.20.0.106
curios_minecraft_version = 1.20.1
curios_version = 5.3.1
ponder_version = 1.0.91
appleskin_minecraft_version = 1.20.1
appleskin_version = 2.5.1

# integration dependency versions
## create addons
## Actually is 1.3.3 but version on version list is this.
create_addition_file = forge-1.20.1-1.3.
## farmers delight addons
farmers_delight_file = 1.20.1-1.3.2
collectors_reap_file = 1.20.1-1.5.5
## 2.1.2
farmers_respite_file = 5543547
miners_delight_file = 1.20.1-1.4.5-backport
## 1.20–1.20.1
nethers_delight_file = MTDQhZd2
corn_delight_file = 5842012
corn_delight_lib_file = 6258665
ends_delight_file = 2.5.1+forge.1.20.1
## abnormals mods addons
blueprint_version = 7.1.2
abnormals_delight_file = 6057626
atmospheric_file = 6248868
autumnity_file = 6151402
buzzier_bees_file = 6151411
environmental_file = 6060255
neapolitan_file = 6248885
upgrade_aquatic_file = 6157694
peculiars_file = 6058169
respiteful_file = 1.3.0
seasonals_file = 6058164
# independent mods
overweight_farming_file = 1.20.1-2.1.0-forge
