# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
# mod version info
mod_version = 1.5.0
artifact_minecraft_version = 1.20.1
minecraft_version = 1.20.1
forge_version = 47.4.22

# build dependency versions
mixin_version = 0.8.7
parchment_version = 2023.09.03

# embedded dependency versions
mixin_extras_version = 0.5.4

# mandatory dependency versions
create_minecraft_version = 1.20.1
create_version = 6.0.8
create_version_number = 291
flywheel_minecraft_version = 1.20.1
flywheel_version = 1.0.6-281
registrate_version = MC1.20-1.3.11
jei_minecraft_version = 1.20.1
jei_version = 15.48.0.185
curios_minecraft_version = 1.20.1
curios_version = 5.14.1
ponder_version = 1.0.92
appleskin_minecraft_version = 1.20.1
appleskin_version = 2.5.1

# integration dependency versions
## create addons
## Actually is 1.3.3 but the published Maven version is truncated.
create_addition_version = forge-1.20.1-1.3.
## farmers delight addons
farmers_delight_version = 1.20.1-1.3.2
collectors_reap_version = 1.20.1-1.5.5
farmers_respite_version = 1.20.1-2.1
miners_delight_version = 1.20.1-1.4.5-backport
nethers_delight_version = 1.20.1-4.0
corn_delight_version = 1.2.11-1.20.1
corn_delight_lib_version = 1.6.34-1.20.1
ends_delight_version = 2.6+forge.1.20.1
## abnormals mods addons
blueprint_version = 7.1.4
abnormals_delight_version = 5.0.1
atmospheric_version = 6.1.1
autumnity_version = 5.0.2
buzzier_bees_version = 6.0.1
gallery_version = 1.0.3
environmental_version = 4.1.2
neapolitan_version = 5.1.0
upgrade_aquatic_version = 6.0.3
peculiars_version = 5.0.0
respiteful_version = 1.4.1
seasonals_version = 5.0.2
# independent mods
overweight_farming_version = 1.20.1-2.1.0-forge
# utility and transitive integration dependencies
botarium_version = 2.3.4
moonlight_version = 1.20-2.16.34-forge
sleep_tight_version = 1.20-1.5.7
patchouli_version = 1.20.1-85-forge
botania_version = 1.20.1-454-forge
ars_nouveau_version = 4.12.7
ars_botania_version = 1.2.0
cc_tweaked_version = 1.120.2
