modLoader="javafml"
loaderVersion="[47,48)"
license="MIT"
issueTrackerURL="https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/issues"
[[mods]]
modId="create_central_kitchen" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Create: Central Kitchen"
displayURL="https://github.com/DragonsPlusMinecraft/CreateCentralKitchen"
authors="LimonBlaze, MarbleGate and Etherwood"
description='''
An add-on for Create, providing automation support for Farmer's Delight and its add-ons.
'''

[[dependencies.create_central_kitchen]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.10,48)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_central_kitchen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_central_kitchen]]
    modId="create"
    mandatory=true
    versionRange="[6.0.8,6.1.0)"
    ordering="AFTER"
    side="BOTH"
