name: Bug Report
description: Create a bug report to help us improve this mod
labels: [ "bug", "triage" ]
body:
  -   type: dropdown
      attributes:
        label: Minecraft Version
        description: The version of Minecraft you were using when the bug occurred
        options:
          - "1.20.1"
          - "1.19.2"
          - "1.18.2"
      validations:
        required: true
  -   type: textarea
      attributes:
        label: Describe the Bug
        description: A clear and concise description of what the bug is.
      validations:
        required: true