name: Feature Request
description: Create a feature request to help us improve this mod
labels: [ "enhancement", "triage" ]
body:
  -   type: textarea
      attributes:
        label: Describe the your request
        description: A clear and concise description of feature request
      validations:
        required: true