@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package plus.dragons.createcentralkitchen.foundation.fluid;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;