@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package plus.dragons.createcentralkitchen.api.block.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;